#!/usr/bin/env bash
set -euxo pipefail

julia --project=binder -e '
using Pkg
Pkg.activate("binder")
# 1) Make the repo package available (local path)
Pkg.develop(PackageSpec(path=pwd()))
# 2) Instantiate & precompile to cut first-open latency
Pkg.instantiate()
Pkg.precompile()
'
